// protoc --go_out=. --go-grpc_out=. --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative  proto/todo/v1/todo.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/todo/v1/todo.proto

package todo_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchTodosOperation int32

const (
	WatchTodosOperation_UNKNOWN WatchTodosOperation = 0
	WatchTodosOperation_CREATED WatchTodosOperation = 1
	WatchTodosOperation_UPDATED WatchTodosOperation = 2
	WatchTodosOperation_DELETED WatchTodosOperation = 3
	WatchTodosOperation_FETCHED WatchTodosOperation = 4
)

// Enum value maps for WatchTodosOperation.
var (
	WatchTodosOperation_name = map[int32]string{
		0: "UNKNOWN",
		1: "CREATED",
		2: "UPDATED",
		3: "DELETED",
		4: "FETCHED",
	}
	WatchTodosOperation_value = map[string]int32{
		"UNKNOWN": 0,
		"CREATED": 1,
		"UPDATED": 2,
		"DELETED": 3,
		"FETCHED": 4,
	}
)

func (x WatchTodosOperation) Enum() *WatchTodosOperation {
	p := new(WatchTodosOperation)
	*p = x
	return p
}

func (x WatchTodosOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchTodosOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_todo_v1_todo_proto_enumTypes[0].Descriptor()
}

func (WatchTodosOperation) Type() protoreflect.EnumType {
	return &file_proto_todo_v1_todo_proto_enumTypes[0]
}

func (x WatchTodosOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatchTodosOperation.Descriptor instead.
func (WatchTodosOperation) EnumDescriptor() ([]byte, []int) {
	return file_proto_todo_v1_todo_proto_rawDescGZIP(), []int{0}
}

type Todo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Completed     bool                   `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	CreatedAt     int32                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int32                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Todo) Reset() {
	*x = Todo{}
	mi := &file_proto_todo_v1_todo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Todo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Todo) ProtoMessage() {}

func (x *Todo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todo_v1_todo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Todo.ProtoReflect.Descriptor instead.
func (*Todo) Descriptor() ([]byte, []int) {
	return file_proto_todo_v1_todo_proto_rawDescGZIP(), []int{0}
}

func (x *Todo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Todo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Todo) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *Todo) GetCreatedAt() int32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Todo) GetUpdatedAt() int32 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreateTodoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTodoRequest) Reset() {
	*x = CreateTodoRequest{}
	mi := &file_proto_todo_v1_todo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTodoRequest) ProtoMessage() {}

func (x *CreateTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todo_v1_todo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTodoRequest.ProtoReflect.Descriptor instead.
func (*CreateTodoRequest) Descriptor() ([]byte, []int) {
	return file_proto_todo_v1_todo_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTodoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type CreateTodoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todo          *Todo                  `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTodoResponse) Reset() {
	*x = CreateTodoResponse{}
	mi := &file_proto_todo_v1_todo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTodoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTodoResponse) ProtoMessage() {}

func (x *CreateTodoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todo_v1_todo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTodoResponse.ProtoReflect.Descriptor instead.
func (*CreateTodoResponse) Descriptor() ([]byte, []int) {
	return file_proto_todo_v1_todo_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTodoResponse) GetTodo() *Todo {
	if x != nil {
		return x.Todo
	}
	return nil
}

type BulkCreateTodosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkCreateTodosResponse) Reset() {
	*x = BulkCreateTodosResponse{}
	mi := &file_proto_todo_v1_todo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkCreateTodosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkCreateTodosResponse) ProtoMessage() {}

func (x *BulkCreateTodosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todo_v1_todo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkCreateTodosResponse.ProtoReflect.Descriptor instead.
func (*BulkCreateTodosResponse) Descriptor() ([]byte, []int) {
	return file_proto_todo_v1_todo_proto_rawDescGZIP(), []int{3}
}

func (x *BulkCreateTodosResponse) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type WatchTodosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     WatchTodosOperation    `protobuf:"varint,1,opt,name=operation,proto3,enum=todo.v1.WatchTodosOperation" json:"operation,omitempty"`
	Todo          *Todo                  `protobuf:"bytes,2,opt,name=todo,proto3" json:"todo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchTodosResponse) Reset() {
	*x = WatchTodosResponse{}
	mi := &file_proto_todo_v1_todo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchTodosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchTodosResponse) ProtoMessage() {}

func (x *WatchTodosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todo_v1_todo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchTodosResponse.ProtoReflect.Descriptor instead.
func (*WatchTodosResponse) Descriptor() ([]byte, []int) {
	return file_proto_todo_v1_todo_proto_rawDescGZIP(), []int{4}
}

func (x *WatchTodosResponse) GetOperation() WatchTodosOperation {
	if x != nil {
		return x.Operation
	}
	return WatchTodosOperation_UNKNOWN
}

func (x *WatchTodosResponse) GetTodo() *Todo {
	if x != nil {
		return x.Todo
	}
	return nil
}

type WatchTodosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OnlyNew       bool                   `protobuf:"varint,1,opt,name=only_new,json=onlyNew,proto3" json:"only_new,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchTodosRequest) Reset() {
	*x = WatchTodosRequest{}
	mi := &file_proto_todo_v1_todo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchTodosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchTodosRequest) ProtoMessage() {}

func (x *WatchTodosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todo_v1_todo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchTodosRequest.ProtoReflect.Descriptor instead.
func (*WatchTodosRequest) Descriptor() ([]byte, []int) {
	return file_proto_todo_v1_todo_proto_rawDescGZIP(), []int{5}
}

func (x *WatchTodosRequest) GetOnlyNew() bool {
	if x != nil {
		return x.OnlyNew
	}
	return false
}

type ListTodosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Completed     bool                   `protobuf:"varint,1,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTodosRequest) Reset() {
	*x = ListTodosRequest{}
	mi := &file_proto_todo_v1_todo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTodosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodosRequest) ProtoMessage() {}

func (x *ListTodosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_todo_v1_todo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTodosRequest.ProtoReflect.Descriptor instead.
func (*ListTodosRequest) Descriptor() ([]byte, []int) {
	return file_proto_todo_v1_todo_proto_rawDescGZIP(), []int{6}
}

func (x *ListTodosRequest) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

var File_proto_todo_v1_todo_proto protoreflect.FileDescriptor

const file_proto_todo_v1_todo_proto_rawDesc = "" +
	"\n" +
	"\x18proto/todo/v1/todo.proto\x12\atodo.v1\"\x88\x01\n" +
	"\x04Todo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1c\n" +
	"\tcompleted\x18\x03 \x01(\bR\tcompleted\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x05R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x05R\tupdatedAt\")\n" +
	"\x11CreateTodoRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\"7\n" +
	"\x12CreateTodoResponse\x12!\n" +
	"\x04todo\x18\x01 \x01(\v2\r.todo.v1.TodoR\x04todo\"+\n" +
	"\x17BulkCreateTodosResponse\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"s\n" +
	"\x12WatchTodosResponse\x12:\n" +
	"\toperation\x18\x01 \x01(\x0e2\x1c.todo.v1.WatchTodosOperationR\toperation\x12!\n" +
	"\x04todo\x18\x02 \x01(\v2\r.todo.v1.TodoR\x04todo\".\n" +
	"\x11WatchTodosRequest\x12\x19\n" +
	"\bonly_new\x18\x01 \x01(\bR\aonlyNew\"0\n" +
	"\x10ListTodosRequest\x12\x1c\n" +
	"\tcompleted\x18\x01 \x01(\bR\tcompleted*V\n" +
	"\x13WatchTodosOperation\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aCREATED\x10\x01\x12\v\n" +
	"\aUPDATED\x10\x02\x12\v\n" +
	"\aDELETED\x10\x03\x12\v\n" +
	"\aFETCHED\x10\x042\xab\x02\n" +
	"\vTodoService\x12E\n" +
	"\n" +
	"CreateTodo\x12\x1a.todo.v1.CreateTodoRequest\x1a\x1b.todo.v1.CreateTodoResponse\x127\n" +
	"\tListTodos\x12\x19.todo.v1.ListTodosRequest\x1a\r.todo.v1.Todo0\x01\x12Q\n" +
	"\x0fBulkCreateTodos\x12\x1a.todo.v1.CreateTodoRequest\x1a .todo.v1.BulkCreateTodosResponse(\x01\x12I\n" +
	"\n" +
	"WatchTodos\x12\x1a.todo.v1.WatchTodosRequest\x1a\x1b.todo.v1.WatchTodosResponse(\x010\x01B\x11Z\x0ftodo/v1;todo_v1b\x06proto3"

var (
	file_proto_todo_v1_todo_proto_rawDescOnce sync.Once
	file_proto_todo_v1_todo_proto_rawDescData []byte
)

func file_proto_todo_v1_todo_proto_rawDescGZIP() []byte {
	file_proto_todo_v1_todo_proto_rawDescOnce.Do(func() {
		file_proto_todo_v1_todo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_todo_v1_todo_proto_rawDesc), len(file_proto_todo_v1_todo_proto_rawDesc)))
	})
	return file_proto_todo_v1_todo_proto_rawDescData
}

var file_proto_todo_v1_todo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_todo_v1_todo_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_todo_v1_todo_proto_goTypes = []any{
	(WatchTodosOperation)(0),        // 0: todo.v1.WatchTodosOperation
	(*Todo)(nil),                    // 1: todo.v1.Todo
	(*CreateTodoRequest)(nil),       // 2: todo.v1.CreateTodoRequest
	(*CreateTodoResponse)(nil),      // 3: todo.v1.CreateTodoResponse
	(*BulkCreateTodosResponse)(nil), // 4: todo.v1.BulkCreateTodosResponse
	(*WatchTodosResponse)(nil),      // 5: todo.v1.WatchTodosResponse
	(*WatchTodosRequest)(nil),       // 6: todo.v1.WatchTodosRequest
	(*ListTodosRequest)(nil),        // 7: todo.v1.ListTodosRequest
}
var file_proto_todo_v1_todo_proto_depIdxs = []int32{
	1, // 0: todo.v1.CreateTodoResponse.todo:type_name -> todo.v1.Todo
	0, // 1: todo.v1.WatchTodosResponse.operation:type_name -> todo.v1.WatchTodosOperation
	1, // 2: todo.v1.WatchTodosResponse.todo:type_name -> todo.v1.Todo
	2, // 3: todo.v1.TodoService.CreateTodo:input_type -> todo.v1.CreateTodoRequest
	7, // 4: todo.v1.TodoService.ListTodos:input_type -> todo.v1.ListTodosRequest
	2, // 5: todo.v1.TodoService.BulkCreateTodos:input_type -> todo.v1.CreateTodoRequest
	6, // 6: todo.v1.TodoService.WatchTodos:input_type -> todo.v1.WatchTodosRequest
	3, // 7: todo.v1.TodoService.CreateTodo:output_type -> todo.v1.CreateTodoResponse
	1, // 8: todo.v1.TodoService.ListTodos:output_type -> todo.v1.Todo
	4, // 9: todo.v1.TodoService.BulkCreateTodos:output_type -> todo.v1.BulkCreateTodosResponse
	5, // 10: todo.v1.TodoService.WatchTodos:output_type -> todo.v1.WatchTodosResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_todo_v1_todo_proto_init() }
func file_proto_todo_v1_todo_proto_init() {
	if File_proto_todo_v1_todo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_todo_v1_todo_proto_rawDesc), len(file_proto_todo_v1_todo_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_todo_v1_todo_proto_goTypes,
		DependencyIndexes: file_proto_todo_v1_todo_proto_depIdxs,
		EnumInfos:         file_proto_todo_v1_todo_proto_enumTypes,
		MessageInfos:      file_proto_todo_v1_todo_proto_msgTypes,
	}.Build()
	File_proto_todo_v1_todo_proto = out.File
	file_proto_todo_v1_todo_proto_goTypes = nil
	file_proto_todo_v1_todo_proto_depIdxs = nil
}
